name: Process Golf Booking Queue

on:
  schedule:
    # Run every morning at 6:55 AM
    - cron: '55 10 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  process-booking-queue:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_AVAILABLE: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # This caches the global npm cache
      
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      
      - name: Cache Playwright browsers
        id: cache-playwright-browsers # Added id
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      
      - name: Install project dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
          
      - name: Install Playwright browser and OS dependencies
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true' # Added conditional
        run: |
          npx playwright install chromium
          npx playwright install-deps chromium
  
      - name: Wait until 7:00 AM
        if: github.event_name == 'schedule'
        run: |
          current_time=$(date +%s)
          target_time=$(date -u -d "today 11:00:00" +%s)
          
          # If current time is already past 11:00 AM UTC, don't wait
          if [ $current_time -lt $target_time ]; then
            sleep_seconds=$((target_time - current_time))
            echo "Waiting for $sleep_seconds seconds until 11:00 AM UTC..."
            sleep $sleep_seconds
          else
            echo "It's already past 11:00 AM UTC, proceeding immediately"
          fi

      - name: Process booking queue
        id: process-queue
        run: |
          npx ts-node process-queue.ts
        env:
          GOLF_USERNAME: ${{ secrets.GOLF_USERNAME }}
          GOLF_PASSWORD: ${{ secrets.GOLF_PASSWORD }}
          DATE_OVERRIDE: ${{ secrets.DATE_OVERRIDE }}
          TAKE_SCREENSHOTS: ${{ secrets.TAKE_SCREENSHOTS }}
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: ${{ env.TAKE_SCREENSHOTS != 'false' }}
        with:
          name: booking-screenshots
          path: logs/*.png
          if-no-files-found: ignore
          retention-days: 7
      
      - name: Commit updated queue
        id: auto_commit_queue # Added id
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update booking queue after processing
          file_pattern: booking-queue.json
      
      - name: Prepare attachments for Discord
        id: prepare_discord_attachments
        if: steps.list_screenshots.outputs.files_list != ''
        run: |
          files_list="${{ steps.list_screenshots.outputs.files_list }}"
          attachments_yaml=""

          OLD_IFS=$IFS
          IFS=','
          read -ra file_paths <<< "$files_list"
          IFS=$OLD_IFS

          for file_path in "${file_paths[@]}"; do
            trimmed_path=$(echo "$file_path" | xargs)
            filename=$(basename "$trimmed_path")
            attachments_yaml+="  - file: ${trimmed_path}\n    filename: ${filename}\n"
          done

          echo "ATTACHMENTS_YAML<<EOF" >> $GITHUB_OUTPUT
          echo -e "${attachments_yaml}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send Images to Discord
        id: discord_webhook
        if: steps.list_screenshots.outputs.files_list != '' && steps.prepare_discord_attachments.outputs.attachments_yaml != ''
        continue-on-error: true  # Don't fail the workflow if Discord posting fails
        uses: MineBartekSA/discord-webhook@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Job finished! Here are the screenshots from the booking process:"
          attachment: |
            ${{ steps.prepare_discord_attachments.outputs.attachments_yaml }}            