name: Process Golf Booking Queue

on:
  schedule:
    # Run every morning at 6:55 AM
    - cron: '55 6 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  process-booking-queue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium
          npx playwright install-deps chromium
  
      - name: Wait until 7:00 AM
        if: github.event_name == 'schedule'
        run: |
          current_time=$(date +%s)
          target_time=$(date -d "today 07:00:00" +%s)
          
          # If current time is already past 7:00 AM, don't wait
          if [ $current_time -lt $target_time ]; then
            sleep_seconds=$((target_time - current_time))
            echo "Waiting for $sleep_seconds seconds until 7:00 AM..."
            sleep $sleep_seconds
          else
            echo "It's already past 7:00 AM, proceeding immediately"
          fi

      - name: Process booking queue
        id: process-queue
        run: |
          npx ts-node process-queue.ts
        env:
          GOLF_USERNAME: ${{ secrets.GOLF_USERNAME }}
          GOLF_PASSWORD: ${{ secrets.GOLF_PASSWORD }}
      
      - name: Commit updated queue
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update booking queue after processing
          file_pattern: booking-queue.json
      